module.exports = [
  // mentions-legales.html
  { file: 'mentions-legales.html', fr: '[Date à compléter à la mise en ligne]', key: 'mentions.date_placeholder', en: '[Date to be completed at launch]', de: '[Datum bei Veröffentlichung noch zu ergänzen]', nl: '[Datum in te vullen bij livegang]' },
  { file: 'mentions-legales.html', fr: 'CONTACT', key: 'mentions.contact_title', en: 'CONTACT', de: 'KONTAKT', nl: 'CONTACT' },
  { file: 'mentions-legales.html', fr: '[Email de contact à compléter]', key: 'mentions.contact_email', en: '[Contact email to be completed]', de: '[Kontakt-E-Mail noch zu ergänzen]', nl: '[Contact e-mail nog aan te vullen]' },
  { file: 'mentions-legales.html', fr: '[Téléphone à compléter]', key: 'mentions.contact_phone', en: '[Phone number to be completed]', de: '[Telefonnummer noch zu ergänzen]', nl: '[Telefoonnummer nog aan te vullen]' },
  { file: 'mentions-legales.html', fr: '[Hébergeur à compléter par le client]', key: 'mentions.host_placeholder', en: '[Hosting provider to be completed by the client]', de: '[Hosting-Anbieter vom Kunden noch zu ergänzen]', nl: '[Hostingprovider in te vullen door de klant]' },
  { file: 'mentions-legales.html', fr: "L'ensemble de ce site relève de la législation française et internationale sur le droit d'auteur et la propriété intellectuelle. Tous les droits de reproduction sont réservés, y compris pour les documents téléchargeables et les représentations iconographiques et photographiques.", key: 'mentions.copyright_laws', en: "The entire site is subject to French and international legislation on copyright and intellectual property. All reproduction rights are reserved, including for downloadable documents and iconographic and photographic representations.", de: "Die gesamte Website unterliegt der französischen und internationalen Gesetzgebung zu Urheberrecht und geistigem Eigentum. Alle Vervielfältigungsrechte sind vorbehalten, einschließlich für herunterladbare Dokumente sowie ikonografische und fotografische Darstellungen.", nl: "De gehele site is onderworpen aan de Franse en internationale wetgeving inzake auteursrecht en intellectueel eigendom. Alle reproductierechten zijn voorbehouden, inclusief voor downloadbare documenten en iconografische en fotografische weergaven." },
  { file: 'mentions-legales.html', fr: 'Pour exercer ces droits, vous pouvez contacter notre Délégué à la Protection des Données (DPO) par email à', key: 'mentions.dpo_contact_1', en: 'To exercise these rights, you can contact our Data Protection Officer (DPO) by email at', de: 'Um diese Rechte auszuüben, können Sie unseren Datenschutzbeauftragten (DPO) per E-Mail kontaktieren unter', nl: 'Om deze rechten uit te oefenen, kunt u per e-mail contact opnemen met onze Functionaris voor Gegevensbescherming (DPO/FG) via' },
  { file: 'mentions-legales.html', fr: "ou par courrier à l'adresse du siège social en joignant une copie d'un titre d'identité.", key: 'mentions.dpo_contact_2', en: "or by mail at the head office address enclosing a copy of an identity document.", de: "oder per Post an die Adresse des Hauptsitzes unter Beifügung einer Kopie eines Ausweisdokuments.", nl: "of per post naar het adres van het hoofdkantoor onder bijvoeging van een kopie van een identiteitsbewijs." },
  { file: 'mentions-legales.html', fr: '[Email du DPO à compléter]', key: 'mentions.dpo_email', en: '[DPO email to be completed]', de: '[E-Mail des Datenschutzbeauftragten noch zu ergänzen]', nl: '[E-mail DPO nog aan te vullen]' },
  
  // cgv.html
  { file: 'cgv.html', fr: 'LÉGAL', key: 'cgv.nav_legal', en: 'LEGAL', de: 'RECHTLICHES', nl: 'JURIDISCH' },
  { file: 'cgv.html', fr: 'Objet', key: 'cgv.nav_objet', en: 'Object', de: 'Gegenstand', nl: 'Voorwerp' },
  { file: 'cgv.html', fr: 'Produits', key: 'cgv.nav_produits', en: 'Products', de: 'Produkte', nl: 'Producten' },
  { file: 'cgv.html', fr: 'Prix et Commande', key: 'cgv.nav_prix', en: 'Price and Order', de: 'Preis und Bestellung', nl: 'Prijs en Bestelling' },
  { file: 'cgv.html', fr: 'Livraison', key: 'cgv.nav_livraison', en: 'Delivery', de: 'Lieferung', nl: 'Levering' },
  { file: 'cgv.html', fr: 'Paiement', key: 'cgv.nav_paiement', en: 'Payment', de: 'Zahlung', nl: 'Betaling' },
  { file: 'cgv.html', fr: 'Rétractation', key: 'cgv.nav_retractation', en: 'Withdrawal', de: 'Widerruf', nl: 'Herroeping' },
  { file: 'cgv.html', fr: 'NOUS CONTACTER', key: 'cgv.nav_contact', en: 'CONTACT US', de: 'KONTAKTIEREN SIE UNS', nl: 'NEEM CONTACT OP' },
  { file: 'cgv.html', fr: 'Elles régissent exclusivement les ventes de bois de chauffage, granulés, et autres produits de biomasse par', key: 'cgv.scope_1', en: 'They exclusively govern the sales of firewood, pellets, and other biomass products by', de: 'Sie regeln ausschließlich den Verkauf von Brennholz, Pellets und anderen Biomasseprodukten durch', nl: 'Ze regelen uitsluitend de verkoop van brandhout, pellets en andere biomassaproducten door' },
  { file: 'cgv.html', fr: "aux acheteurs professionnels (B2B). Toute commande implique l'acceptation sans réserve de ces conditions par l'acheteur, nonobstant toute stipulation contraire figurant dans ses propres conditions générales d'achat.", key: 'cgv.scope_2', en: "to professional buyers (B2B). Any order implies unconditional acceptance of these conditions by the buyer, notwithstanding any contrary stipulation in their own general purchasing conditions.", de: "an professionelle Käufer (B2B). Jede Bestellung impliziert die vorbehaltlose Annahme dieser Bedingungen durch den Käufer, ungeachtet entgegenstehender Bestimmungen in dessen eigenen allgemeinen Einkaufsbedingungen.", nl: "aan professionele kopers (B2B). Elke bestelling impliceert de onvoorwaardelijke aanvaarding van deze voorwaarden door de koper, ongeacht eventuele andersluidende bepalingen in diens eigen algemene inkoopvoorwaarden." },
  { file: 'cgv.html', fr: "CONDITIONS D'ACCÈS OBLIGATOIRES", key: 'cgv.access_conditions', en: "MANDATORY ACCESS CONDITIONS", de: "ZUSATZBEDINGUNGEN FÜR DEN ZUGANG", nl: "VERPLICHTE TOEGANGSVOORWAARDEN" },
  
  // politique-confidentialite.html
  { file: 'politique-confidentialite.html', fr: '[Email du DPO à compléter]', key: 'privacy.dpo_email', en: '[DPO email to be completed]', de: '[E-Mail des Datenschutzbeauftragten noch zu ergänzen]', nl: '[E-mail DPO nog aan te vullen]' },
  { file: 'politique-confidentialite.html', fr: 'Exécution du contrat', key: 'privacy.execution_contract', en: 'Execution of the contract', de: 'Vertragserfüllung', nl: 'Uitvoering van de overeenkomst' },
  { file: 'politique-confidentialite.html', fr: 'Gérer les préférences', key: 'privacy.manage_preferences', en: 'Manage preferences', de: 'Präferenzen verwalten', nl: 'Voorkeuren beheren' },
  { file: 'politique-confidentialite.html', fr: 'Contacter le DPO', key: 'privacy.contact_dpo', en: 'Contact the DPO', de: 'DPO kontaktieren', nl: 'Neem contact op met de DPO' },
  
  // politique-retour.html
  { file: 'politique-retour.html', fr: 'Conditions Générales', key: 'return.nav_conditions', en: 'General Conditions', de: 'Allgemeine Bedingungen', nl: 'Algemene Voorwaarden' },
  { file: 'politique-retour.html', fr: 'Logistique & Transport', key: 'return.nav_logistics', en: 'Logistics & Transport', de: 'Logistik & Transport', nl: 'Logistiek & Transport' },
  { file: 'politique-retour.html', fr: 'Processus de Remboursement', key: 'return.nav_refund', en: 'Refund Process', de: 'Erstattungsprozess', nl: 'Terugbetalingsproces' },
  { file: 'politique-retour.html', fr: 'Exceptions & Litiges', key: 'return.nav_exceptions', en: 'Exceptions & Disputes', de: 'Ausnahmen & Streitigkeiten', nl: 'Uitzonderingen & Geschillen' },
  { file: 'politique-retour.html', fr: 'Contacter le SAV', key: 'return.contact_support', en: 'Contact Support', de: 'Kundendienst kontaktieren', nl: 'Neem contact op met de klantenservice' },
  { file: 'politique-retour.html', fr: "En raison de la nature volumineuse et des coûts logistiques associés à nos produits (palettes de bois, big bags de granulés), les retours sont soumis à des conditions strictes. Vous disposez d'un délai légal de", key: 'return.policy_1', en: "Due to the bulky nature and logistical costs associated with our products (wood pallets, pellet big bags), returns are subject to strict conditions. You have a legal period of", de: "Aufgrund der Sperrigkeit und der mit unseren Produkten verbundenen Logistikkosten (Holzpaletten, Pellet-Big-Bags) unterliegen Rücksendungen strengen Bedingungen. Sie haben eine gesetzliche Frist von", nl: "Vanwege de omvang en de logistieke kosten die aan onze producten (houtpallets, big bags pellets) zijn verbonden, zijn retouren onderworpen aan strikte voorwaarden. U heeft een wettelijke termijn van" },
  { file: 'politique-retour.html', fr: 'à compter de la date de livraison pour exercer votre droit de rétractation.', key: 'return.policy_2', en: 'from the delivery date to exercise your right of withdrawal.', de: 'ab dem Lieferdatum, um Ihr Widerrufsrecht auszuüben.', nl: 'vanaf de leveringsdatum om uw herroepingsrecht uit te oefenen.' },
  { file: 'politique-retour.html', fr: "Critères d'acceptation", key: 'return.acceptance_criteria', en: 'Acceptance criteria', de: 'Annahmekriterien', nl: 'Acceptatiecriteria' }
];
